name: skinvision
description: "Teste de aplicação"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.10.0
  firebase_core: ^3.13.0
  image_picker: ^1.1.2
  image_cropper: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
