// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBydfyFKuNGzgZBOsUqSQW7CcJ3_S12-1Q',
    appId: '1:351649700878:web:097ac39bfb647239c4f05f',
    messagingSenderId: '351649700878',
    projectId: 'skinexemple',
    authDomain: 'skinexemple.firebaseapp.com',
    storageBucket: 'skinexemple.firebasestorage.app',
    measurementId: 'G-3D3FX2Z5X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmZTUiPyuLOyK-DfkvDrJ8_K0hnAs9Th8',
    appId: '1:351649700878:android:b976a5ccba8183cbc4f05f',
    messagingSenderId: '351649700878',
    projectId: 'skinexemple',
    storageBucket: 'skinexemple.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZRBMU0dqjJUQsEcPgB14pfg8cV7YFo0s',
    appId: '1:351649700878:ios:748a9f6e0cbe0d09c4f05f',
    messagingSenderId: '351649700878',
    projectId: 'skinexemple',
    storageBucket: 'skinexemple.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZRBMU0dqjJUQsEcPgB14pfg8cV7YFo0s',
    appId: '1:351649700878:ios:748a9f6e0cbe0d09c4f05f',
    messagingSenderId: '351649700878',
    projectId: 'skinexemple',
    storageBucket: 'skinexemple.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBydfyFKuNGzgZBOsUqSQW7CcJ3_S12-1Q',
    appId: '1:351649700878:web:e7279ad1772a8f0fc4f05f',
    messagingSenderId: '351649700878',
    projectId: 'skinexemple',
    authDomain: 'skinexemple.firebaseapp.com',
    storageBucket: 'skinexemple.firebasestorage.app',
    measurementId: 'G-ZPVZHYBWZZ',
  );
}
